header:
  - identifier: members
    name: Members
    url: /en-us/membros/
    weight: 1
  - identifier: about
    name: About
    url: /en-us/sobre/
    weight: 2
  - identifier: events
    name: Events
    url: /en-us/eventos/
    weight: 3
  - identifier: contact
    name: Contact
    url: /en-us/contato/
    weight: 5
  - identifier: dump-zine
    name: Articles
    url: /en-us/dump-zine/
    weight: 4

legal:
  - identifier: privacy
    name: Privacy Policy
    url: /en-us/legal/privacy/
    weight: 1
  - identifier: terms
    name: Terms of Use
    url: /en-us/legal/terms/
    weight: 1